name: pyapprox-base
channels:
  - defaults
  - conda-forge
dependencies:
  - python >3.6,<3.9 # numba does requires <=3.8
  - numpy>=1.20 # numba requires numpy >1.17, <=1.20 but pandas requires >= 1.20
  - matplotlib
  - scipy
  - jupyter
  - pytest
  - pytest-cov
  - pip
  - setuptools
  - scikit-learn
  - Cython
  - sympy
  - networkx
  - pytorch
  - pymc3 # requires conda-forge
  - tqdm
  - numba
  # make html in docs folder
  - sphinx
#  - sphinx-gallery # requires conda-forge
  - pip:
    - sphinx-gallery
    - sphinx_copybutton
    - sphinx_rtd_theme
    - numpydoc
    - sphinx_automodapi
